# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FootBallNew' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	platform :ios, '7.0'
	pod 'Firebase'

  # Pods for FootBallNew

  target 'FootBallNewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FootBallNewUITests' do
    inherit! :search_paths
    # Pods for testing
  end



end
